# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combin.ui'
#
# Created: Wed Nov  9 13:09:58 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_combin(object):
    def setupUi(self, combin):
        combin.setObjectName("combin")
        combin.resize(500, 420)
        combin.setFrameShape(QtGui.QFrame.StyledPanel)
        combin.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(combin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(combin)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.setsBox = QtGui.QComboBox(self.groupBox)
        self.setsBox.setObjectName("setsBox")
        self.gridLayout.addWidget(self.setsBox, 0, 0, 1, 2)
        self.addSetButton = QtGui.QPushButton(self.groupBox)
        self.addSetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addSetButton.setObjectName("addSetButton")
        self.gridLayout.addWidget(self.addSetButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.combinSets = QtGui.QGroupBox(combin)
        self.combinSets.setObjectName("combinSets")
        self.combinLayout = QtGui.QVBoxLayout(self.combinSets)
        self.combinLayout.setObjectName("combinLayout")
        self.verticalLayout.addWidget(self.combinSets)
        self.frame = QtGui.QFrame(combin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clearButton = QtGui.QPushButton(self.frame)
        self.clearButton.setEnabled(False)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox_3 = QtGui.QGroupBox(combin)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.operationBox = QtGui.QComboBox(self.groupBox_3)
        self.operationBox.setObjectName("operationBox")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.gridLayout_2.addWidget(self.operationBox, 1, 0, 1, 1)
        self.complementaryBox = QtGui.QComboBox(self.groupBox_3)
        self.complementaryBox.setObjectName("complementaryBox")
        self.complementaryBox.addItem("")
        self.complementaryBox.addItem("")
        self.gridLayout_2.addWidget(self.complementaryBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(combin)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.operationLine = QtGui.QLineEdit(self.groupBox_4)
        self.operationLine.setObjectName("operationLine")
        self.gridLayout_3.addWidget(self.operationLine, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/help.gif"))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(combin)
        QtCore.QMetaObject.connectSlotsByName(combin)

    def retranslateUi(self, combin):
        combin.setWindowTitle(QtGui.QApplication.translate("combin", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("combin", "Sets in Session", None, QtGui.QApplication.UnicodeUTF8))
        self.addSetButton.setText(QtGui.QApplication.translate("combin", "Add Set to List", None, QtGui.QApplication.UnicodeUTF8))
        self.combinSets.setTitle(QtGui.QApplication.translate("combin", "Combin Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("combin", "Clear Combin Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("combin", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(0, QtGui.QApplication.translate("combin", "Inside", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(1, QtGui.QApplication.translate("combin", "Outside", None, QtGui.QApplication.UnicodeUTF8))
        self.complementaryBox.setItemText(0, QtGui.QApplication.translate("combin", "Blanks", None, QtGui.QApplication.UnicodeUTF8))
        self.complementaryBox.setItemText(1, QtGui.QApplication.translate("combin", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("combin", "Operation Box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("combin", "Operation in complementary box", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("combin", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("combin", "Operation", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc
