# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ellint.ui'
#
# Created: Tue Mar  3 12:53:28 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ellint(object):
    def setupUi(self, ellint):
        ellint.setObjectName(_fromUtf8("ellint"))
        ellint.resize(700, 572)
        ellint.setFrameShape(QtGui.QFrame.StyledPanel)
        ellint.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(ellint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(ellint)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.massLabel = QtGui.QLabel(ellint)
        self.massLabel.setEnabled(False)
        self.massLabel.setObjectName(_fromUtf8("massLabel"))
        self.gridLayout.addWidget(self.massLabel, 8, 0, 1, 1)
        self.xcentreLine = QtGui.QLineEdit(ellint)
        self.xcentreLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xcentreLine.setObjectName(_fromUtf8("xcentreLine"))
        self.gridLayout.addWidget(self.xcentreLine, 0, 1, 1, 1)
        self.distanceLine = QtGui.QLineEdit(ellint)
        self.distanceLine.setEnabled(False)
        self.distanceLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.distanceLine.setObjectName(_fromUtf8("distanceLine"))
        self.gridLayout.addWidget(self.distanceLine, 10, 1, 1, 1)
        self.label_6 = QtGui.QLabel(ellint)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.orderBox = QtGui.QComboBox(ellint)
        self.orderBox.setObjectName(_fromUtf8("orderBox"))
        self.orderBox.addItem(_fromUtf8(""))
        self.orderBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.orderBox, 2, 4, 1, 2)
        self.xsubpixLine = QtGui.QLineEdit(ellint)
        self.xsubpixLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.xsubpixLine.setObjectName(_fromUtf8("xsubpixLine"))
        self.gridLayout.addWidget(self.xsubpixLine, 8, 4, 1, 1)
        self.label = QtGui.QLabel(ellint)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(ellint)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.radiiLine = QtGui.QLineEdit(ellint)
        self.radiiLine.setObjectName(_fromUtf8("radiiLine"))
        self.gridLayout.addWidget(self.radiiLine, 3, 1, 1, 4)
        self.label_8 = QtGui.QLabel(ellint)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.paLine = QtGui.QLineEdit(ellint)
        self.paLine.setObjectName(_fromUtf8("paLine"))
        self.gridLayout.addWidget(self.paLine, 5, 1, 1, 4)
        self.rangeLabel = QtGui.QLabel(ellint)
        self.rangeLabel.setEnabled(False)
        self.rangeLabel.setText(_fromUtf8(""))
        self.rangeLabel.setObjectName(_fromUtf8("rangeLabel"))
        self.gridLayout.addWidget(self.rangeLabel, 1, 3, 1, 1)
        self.radiiButton = QtGui.QPushButton(ellint)
        self.radiiButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radiiButton.setIcon(icon)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName(_fromUtf8("radiiButton"))
        self.gridLayout.addWidget(self.radiiButton, 3, 5, 1, 1)
        self.label_5 = QtGui.QLabel(ellint)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.widthLine = QtGui.QLineEdit(ellint)
        self.widthLine.setObjectName(_fromUtf8("widthLine"))
        self.gridLayout.addWidget(self.widthLine, 4, 1, 1, 4)
        self.checkSampRadii = QtGui.QCheckBox(ellint)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampRadii.setObjectName(_fromUtf8("checkSampRadii"))
        self.gridLayout.addWidget(self.checkSampRadii, 3, 6, 1, 1)
        self.optionBox = QtGui.QComboBox(ellint)
        self.optionBox.setObjectName(_fromUtf8("optionBox"))
        self.optionBox.addItem(_fromUtf8(""))
        self.optionBox.addItem(_fromUtf8(""))
        self.optionBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.optionBox, 2, 1, 1, 2)
        self.distanceLabel = QtGui.QLabel(ellint)
        self.distanceLabel.setEnabled(False)
        self.distanceLabel.setObjectName(_fromUtf8("distanceLabel"))
        self.gridLayout.addWidget(self.distanceLabel, 10, 0, 1, 1)
        self.ysubpixLine = QtGui.QLineEdit(ellint)
        self.ysubpixLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.ysubpixLine.setObjectName(_fromUtf8("ysubpixLine"))
        self.gridLayout.addWidget(self.ysubpixLine, 8, 5, 1, 1)
        self.label_3 = QtGui.QLabel(ellint)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.mpcLabel = QtGui.QLabel(ellint)
        self.mpcLabel.setEnabled(False)
        self.mpcLabel.setObjectName(_fromUtf8("mpcLabel"))
        self.gridLayout.addWidget(self.mpcLabel, 10, 2, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(ellint)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName(_fromUtf8("checkSampCentre"))
        self.gridLayout.addWidget(self.checkSampCentre, 0, 3, 1, 1)
        self.moLabel = QtGui.QLabel(ellint)
        self.moLabel.setEnabled(False)
        self.moLabel.setObjectName(_fromUtf8("moLabel"))
        self.gridLayout.addWidget(self.moLabel, 8, 2, 1, 1)
        self.inclLine = QtGui.QLineEdit(ellint)
        self.inclLine.setObjectName(_fromUtf8("inclLine"))
        self.gridLayout.addWidget(self.inclLine, 6, 1, 1, 4)
        self.label_11 = QtGui.QLabel(ellint)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.paButton = QtGui.QPushButton(ellint)
        self.paButton.setText(_fromUtf8(""))
        self.paButton.setIcon(icon)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName(_fromUtf8("paButton"))
        self.gridLayout.addWidget(self.paButton, 5, 5, 1, 1)
        self.ycentreLine = QtGui.QLineEdit(ellint)
        self.ycentreLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ycentreLine.setObjectName(_fromUtf8("ycentreLine"))
        self.gridLayout.addWidget(self.ycentreLine, 0, 2, 1, 1)
        self.widthButton = QtGui.QPushButton(ellint)
        self.widthButton.setText(_fromUtf8(""))
        self.widthButton.setIcon(icon)
        self.widthButton.setIconSize(QtCore.QSize(20, 20))
        self.widthButton.setObjectName(_fromUtf8("widthButton"))
        self.gridLayout.addWidget(self.widthButton, 4, 5, 1, 1)
        self.label_4 = QtGui.QLabel(ellint)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.overlapCheck = QtGui.QCheckBox(ellint)
        self.overlapCheck.setChecked(True)
        self.overlapCheck.setObjectName(_fromUtf8("overlapCheck"))
        self.gridLayout.addWidget(self.overlapCheck, 10, 3, 1, 1)
        self.massLine = QtGui.QLineEdit(ellint)
        self.massLine.setEnabled(False)
        self.massLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.massLine.setObjectName(_fromUtf8("massLine"))
        self.gridLayout.addWidget(self.massLine, 8, 1, 1, 1)
        self.inclButton = QtGui.QPushButton(ellint)
        self.inclButton.setText(_fromUtf8(""))
        self.inclButton.setIcon(icon)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName(_fromUtf8("inclButton"))
        self.gridLayout.addWidget(self.inclButton, 6, 5, 1, 1)
        self.xrangeLine = QtGui.QLineEdit(ellint)
        self.xrangeLine.setEnabled(True)
        self.xrangeLine.setMinimumSize(QtCore.QSize(125, 0))
        self.xrangeLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xrangeLine.setObjectName(_fromUtf8("xrangeLine"))
        self.gridLayout.addWidget(self.xrangeLine, 1, 1, 1, 1)
        self.yrangeLine = QtGui.QLineEdit(ellint)
        self.yrangeLine.setEnabled(True)
        self.yrangeLine.setMinimumSize(QtCore.QSize(125, 0))
        self.yrangeLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.yrangeLine.setObjectName(_fromUtf8("yrangeLine"))
        self.gridLayout.addWidget(self.yrangeLine, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(ellint)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 8, 3, 1, 1)
        self.frame = QtGui.QFrame(ellint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadParamsButton = QtGui.QPushButton(self.frame)
        self.loadParamsButton.setObjectName(_fromUtf8("loadParamsButton"))
        self.horizontalLayout.addWidget(self.loadParamsButton)
        self.saveParamsButton = QtGui.QPushButton(self.frame)
        self.saveParamsButton.setObjectName(_fromUtf8("saveParamsButton"))
        self.horizontalLayout.addWidget(self.saveParamsButton)
        self.gridLayout.addWidget(self.frame, 11, 1, 1, 2)
        self.getRotcurColumnsButton = QtGui.QPushButton(ellint)
        self.getRotcurColumnsButton.setObjectName(_fromUtf8("getRotcurColumnsButton"))
        self.gridLayout.addWidget(self.getRotcurColumnsButton, 11, 5, 1, 2)
        self.segmentList = QtGui.QListWidget(ellint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentList.sizePolicy().hasHeightForWidth())
        self.segmentList.setSizePolicy(sizePolicy)
        self.segmentList.setObjectName(_fromUtf8("segmentList"))
        item = QtGui.QListWidgetItem()
        self.segmentList.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.segmentList.addItem(item)
        self.gridLayout.addWidget(self.segmentList, 7, 1, 1, 4)

        self.retranslateUi(ellint)
        QtCore.QMetaObject.connectSlotsByName(ellint)

    def retranslateUi(self, ellint):
        ellint.setWindowTitle(_translate("ellint", "Frame", None))
        self.label_9.setText(_translate("ellint", "WIDTH", None))
        self.massLabel.setText(_translate("ellint", "MASS", None))
        self.label_6.setText(_translate("ellint", "ORDER", None))
        self.orderBox.setItemText(0, _translate("ellint", "Segments in rings", None))
        self.orderBox.setItemText(1, _translate("ellint", "Rings in segments", None))
        self.label.setText(_translate("ellint", "SEGMENTS", None))
        self.label_10.setText(_translate("ellint", "PA", None))
        self.label_8.setText(_translate("ellint", "RADII", None))
        self.label_5.setText(_translate("ellint", "OPTION", None))
        self.checkSampRadii.setText(_translate("ellint", "SAMP", None))
        self.optionBox.setItemText(0, _translate("ellint", "Stats", None))
        self.optionBox.setItemText(1, _translate("ellint", "Surface brightness", None))
        self.optionBox.setItemText(2, _translate("ellint", "Mass surface density", None))
        self.distanceLabel.setText(_translate("ellint", "DISTANCE", None))
        self.label_3.setText(_translate("ellint", "RANGE", None))
        self.mpcLabel.setText(_translate("ellint", "Mpc", None))
        self.checkSampCentre.setText(_translate("ellint", "SAMP", None))
        self.moLabel.setText(_translate("ellint", "Mo", None))
        self.label_11.setText(_translate("ellint", "INCL", None))
        self.label_4.setText(_translate("ellint", "CENTRE", None))
        self.overlapCheck.setText(_translate("ellint", "OVERLAP", None))
        self.label_15.setText(_translate("ellint", "SUBPIX", None))
        self.loadParamsButton.setText(_translate("ellint", "Load values", None))
        self.saveParamsButton.setText(_translate("ellint", "Save values", None))
        self.getRotcurColumnsButton.setText(_translate("ellint", "Load rotcur set table", None))
        __sortingEnabled = self.segmentList.isSortingEnabled()
        self.segmentList.setSortingEnabled(False)
        item = self.segmentList.item(0)
        item.setText(_translate("ellint", "0 360", None))
        self.segmentList.setSortingEnabled(__sortingEnabled)

import resources_rc
