# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galmod.ui'
#
# Created: Thu Apr 25 10:59:41 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_galmod(object):
    def setupUi(self, galmod):
        galmod.setObjectName("galmod")
        galmod.resize(628, 529)
        galmod.setFrameShape(QtGui.QFrame.StyledPanel)
        galmod.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(galmod)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(galmod)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(galmod)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(galmod)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.radiiLine = QtGui.QLineEdit(galmod)
        self.radiiLine.setObjectName("radiiLine")
        self.gridLayout.addWidget(self.radiiLine, 3, 1, 1, 5)
        self.label_4 = QtGui.QLabel(galmod)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.vrotLine = QtGui.QLineEdit(galmod)
        self.vrotLine.setObjectName("vrotLine")
        self.gridLayout.addWidget(self.vrotLine, 4, 1, 1, 5)
        self.vrotButton = QtGui.QPushButton(galmod)
        self.vrotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vrotButton.setIcon(icon)
        self.vrotButton.setIconSize(QtCore.QSize(20, 20))
        self.vrotButton.setObjectName("vrotButton")
        self.gridLayout.addWidget(self.vrotButton, 4, 6, 1, 1)
        self.label_5 = QtGui.QLabel(galmod)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.vdispLine = QtGui.QLineEdit(galmod)
        self.vdispLine.setObjectName("vdispLine")
        self.gridLayout.addWidget(self.vdispLine, 5, 1, 1, 5)
        self.vdispButton = QtGui.QPushButton(galmod)
        self.vdispButton.setText("")
        self.vdispButton.setIcon(icon)
        self.vdispButton.setIconSize(QtCore.QSize(20, 20))
        self.vdispButton.setObjectName("vdispButton")
        self.gridLayout.addWidget(self.vdispButton, 5, 6, 1, 1)
        self.label_6 = QtGui.QLabel(galmod)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.densLine = QtGui.QLineEdit(galmod)
        self.densLine.setObjectName("densLine")
        self.gridLayout.addWidget(self.densLine, 6, 1, 1, 5)
        self.densButton = QtGui.QPushButton(galmod)
        self.densButton.setText("")
        self.densButton.setIcon(icon)
        self.densButton.setIconSize(QtCore.QSize(20, 20))
        self.densButton.setObjectName("densButton")
        self.gridLayout.addWidget(self.densButton, 6, 6, 1, 1)
        self.label_7 = QtGui.QLabel(galmod)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.zoLine = QtGui.QLineEdit(galmod)
        self.zoLine.setObjectName("zoLine")
        self.gridLayout.addWidget(self.zoLine, 7, 1, 1, 5)
        self.zoButton = QtGui.QPushButton(galmod)
        self.zoButton.setText("")
        self.zoButton.setIcon(icon)
        self.zoButton.setIconSize(QtCore.QSize(20, 20))
        self.zoButton.setObjectName("zoButton")
        self.gridLayout.addWidget(self.zoButton, 7, 6, 1, 1)
        self.label_8 = QtGui.QLabel(galmod)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.inclLine = QtGui.QLineEdit(galmod)
        self.inclLine.setObjectName("inclLine")
        self.gridLayout.addWidget(self.inclLine, 8, 1, 1, 5)
        self.inclButton = QtGui.QPushButton(galmod)
        self.inclButton.setText("")
        self.inclButton.setIcon(icon)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName("inclButton")
        self.gridLayout.addWidget(self.inclButton, 8, 6, 1, 1)
        self.label_9 = QtGui.QLabel(galmod)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.paLine = QtGui.QLineEdit(galmod)
        self.paLine.setObjectName("paLine")
        self.gridLayout.addWidget(self.paLine, 9, 1, 1, 5)
        self.paButton = QtGui.QPushButton(galmod)
        self.paButton.setText("")
        self.paButton.setIcon(icon)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName("paButton")
        self.gridLayout.addWidget(self.paButton, 9, 6, 1, 1)
        self.label_10 = QtGui.QLabel(galmod)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.cdensLine = QtGui.QLineEdit(galmod)
        self.cdensLine.setObjectName("cdensLine")
        self.gridLayout.addWidget(self.cdensLine, 10, 1, 1, 1)
        self.label_11 = QtGui.QLabel(galmod)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 3, 1, 1)
        self.label_12 = QtGui.QLabel(galmod)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 4, 1, 1)
        self.nvLine = QtGui.QLineEdit(galmod)
        self.nvLine.setObjectName("nvLine")
        self.gridLayout.addWidget(self.nvLine, 10, 5, 1, 1)
        self.label_13 = QtGui.QLabel(galmod)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 3, 1, 1)
        self.layerBox = QtGui.QComboBox(galmod)
        self.layerBox.setObjectName("layerBox")
        self.layerBox.addItem("")
        self.layerBox.addItem("")
        self.layerBox.addItem("")
        self.layerBox.addItem("")
        self.layerBox.addItem("")
        self.gridLayout.addWidget(self.layerBox, 11, 4, 1, 2)
        self.label_14 = QtGui.QLabel(galmod)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 13, 0, 1, 1)
        self.iseedLine = QtGui.QLineEdit(galmod)
        self.iseedLine.setObjectName("iseedLine")
        self.gridLayout.addWidget(self.iseedLine, 13, 1, 1, 1)
        self.radiiButton = QtGui.QPushButton(galmod)
        self.radiiButton.setText("")
        self.radiiButton.setIcon(icon)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName("radiiButton")
        self.gridLayout.addWidget(self.radiiButton, 3, 6, 1, 1)
        self.saveParamsButton = QtGui.QPushButton(galmod)
        self.saveParamsButton.setObjectName("saveParamsButton")
        self.gridLayout.addWidget(self.saveParamsButton, 14, 0, 1, 1)
        self.loadParamsButton = QtGui.QPushButton(galmod)
        self.loadParamsButton.setObjectName("loadParamsButton")
        self.gridLayout.addWidget(self.loadParamsButton, 14, 1, 1, 1)
        self.cmode0Radio = QtGui.QRadioButton(galmod)
        self.cmode0Radio.setChecked(True)
        self.cmode0Radio.setObjectName("cmode0Radio")
#        #self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8) = QtGui.QButtonGroup(galmod)
#        self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8).setObjectName("QtGui.QApplication.translate(\"galmod\", \"buttonGroup1\", None, QtGui.QApplication.UnicodeUTF8)")
#        self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8).addButton(self.cmode0Radio)
        self.gridLayout.addWidget(self.cmode0Radio, 11, 1, 1, 1)
        self.cmode1Radio = QtGui.QRadioButton(galmod)
        self.cmode1Radio.setObjectName("cmode1Radio")
#        #self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8) = QtGui.QButtonGroup(galmod)
#        self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8).setObjectName("QtGui.QApplication.translate(\"galmod\", \"buttonGroup1\", None, QtGui.QApplication.UnicodeUTF8)")
#        self.QtGui.QApplication.translate("galmod", "buttonGroup1", None, QtGui.QApplication.UnicodeUTF8).addButton(self.cmode1Radio)
        self.gridLayout.addWidget(self.cmode1Radio, 12, 1, 1, 1)
        self.frame = QtGui.QFrame(galmod)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xcentreLine = QtGui.QLineEdit(self.frame)
        self.xcentreLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.xcentreLine.setObjectName("xcentreLine")
        self.horizontalLayout.addWidget(self.xcentreLine)
        self.ycentreLine = QtGui.QLineEdit(self.frame)
        self.ycentreLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.ycentreLine.setObjectName("ycentreLine")
        self.horizontalLayout.addWidget(self.ycentreLine)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(galmod)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vsysLine = QtGui.QLineEdit(self.frame_2)
        self.vsysLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vsysLine.setObjectName("vsysLine")
        self.horizontalLayout_2.addWidget(self.vsysLine)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 2)
        self.label_16 = QtGui.QLabel(galmod)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.drvalLine = QtGui.QLineEdit(galmod)
        self.drvalLine.setObjectName("drvalLine")
        self.gridLayout.addWidget(self.drvalLine, 2, 1, 1, 2)
        self.emptyCheck = QtGui.QCheckBox(galmod)
        self.emptyCheck.setChecked(True)
        self.emptyCheck.setObjectName("emptyCheck")
        self.gridLayout.addWidget(self.emptyCheck, 1, 3, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(galmod)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet("QCheckBox { color: green }")
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName("checkSampCentre")
        self.gridLayout.addWidget(self.checkSampCentre, 0, 3, 1, 1)
        self.checkSampVsys = QtGui.QCheckBox(galmod)
        self.checkSampVsys.setEnabled(False)
        self.checkSampVsys.setStyleSheet("QCheckBox { color: green }")
        self.checkSampVsys.setObjectName("checkSampVsys")
        self.gridLayout.addWidget(self.checkSampVsys, 1, 4, 1, 1)
        self.checkSampRadii = QtGui.QCheckBox(galmod)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet("QCheckBox { color: green }")
        self.checkSampRadii.setObjectName("checkSampRadii")
        self.gridLayout.addWidget(self.checkSampRadii, 3, 7, 1, 1)
        self.checkSampVrot = QtGui.QCheckBox(galmod)
        self.checkSampVrot.setEnabled(False)
        self.checkSampVrot.setStyleSheet("QCheckBox { color: green }")
        self.checkSampVrot.setObjectName("checkSampVrot")
        self.gridLayout.addWidget(self.checkSampVrot, 4, 7, 1, 1)

        self.retranslateUi(galmod)
        QtCore.QMetaObject.connectSlotsByName(galmod)

    def retranslateUi(self, galmod):
        galmod.setWindowTitle(QtGui.QApplication.translate("galmod", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("galmod", "CENTRE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("galmod", "VSYS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("galmod", "RADII", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("galmod", "VROT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("galmod", "VDISP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("galmod", "DENS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("galmod", "Z0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("galmod", "INCL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("galmod", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("galmod", "CDENS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("galmod", "10^20 atoms/cm^2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("galmod", "NV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("galmod", "Layer Type", None, QtGui.QApplication.UnicodeUTF8))
        self.layerBox.setItemText(0, QtGui.QApplication.translate("galmod", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.layerBox.setItemText(1, QtGui.QApplication.translate("galmod", "Sech2", None, QtGui.QApplication.UnicodeUTF8))
        self.layerBox.setItemText(2, QtGui.QApplication.translate("galmod", "Exponential", None, QtGui.QApplication.UnicodeUTF8))
        self.layerBox.setItemText(3, QtGui.QApplication.translate("galmod", "Lorentzian", None, QtGui.QApplication.UnicodeUTF8))
        self.layerBox.setItemText(4, QtGui.QApplication.translate("galmod", "Box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("galmod", "ISEED", None, QtGui.QApplication.UnicodeUTF8))
        self.saveParamsButton.setText(QtGui.QApplication.translate("galmod", "SAVE PARMAS", None, QtGui.QApplication.UnicodeUTF8))
        self.loadParamsButton.setText(QtGui.QApplication.translate("galmod", "LOAD PARAMS", None, QtGui.QApplication.UnicodeUTF8))
        self.cmode0Radio.setText(QtGui.QApplication.translate("galmod", "CMODE 0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmode1Radio.setText(QtGui.QApplication.translate("galmod", "CMODE 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("galmod", "KM/S", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("galmod", "DRVAL3", None, QtGui.QApplication.UnicodeUTF8))
        self.emptyCheck.setText(QtGui.QApplication.translate("galmod", "EMPTY", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampCentre.setText(QtGui.QApplication.translate("galmod", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVsys.setText(QtGui.QApplication.translate("galmod", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampRadii.setText(QtGui.QApplication.translate("galmod", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVrot.setText(QtGui.QApplication.translate("galmod", "SAMP", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
