# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galmod.ui'
#
# Created: Tue Mar  3 12:53:37 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_galmod(object):
    def setupUi(self, galmod):
        galmod.setObjectName(_fromUtf8("galmod"))
        galmod.resize(684, 543)
        galmod.setFrameShape(QtGui.QFrame.StyledPanel)
        galmod.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(galmod)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.densLine = QtGui.QLineEdit(galmod)
        self.densLine.setObjectName(_fromUtf8("densLine"))
        self.gridLayout.addWidget(self.densLine, 6, 1, 1, 5)
        self.label_4 = QtGui.QLabel(galmod)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(galmod)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName(_fromUtf8("checkSampCentre"))
        self.gridLayout.addWidget(self.checkSampCentre, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(galmod)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.checkSampRadii = QtGui.QCheckBox(galmod)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampRadii.setObjectName(_fromUtf8("checkSampRadii"))
        self.gridLayout.addWidget(self.checkSampRadii, 3, 7, 1, 1)
        self.label_9 = QtGui.QLabel(galmod)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.checkSampVrot = QtGui.QCheckBox(galmod)
        self.checkSampVrot.setEnabled(False)
        self.checkSampVrot.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVrot.setObjectName(_fromUtf8("checkSampVrot"))
        self.gridLayout.addWidget(self.checkSampVrot, 4, 7, 1, 1)
        self.densButton = QtGui.QPushButton(galmod)
        self.densButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.densButton.setIcon(icon)
        self.densButton.setIconSize(QtCore.QSize(20, 20))
        self.densButton.setObjectName(_fromUtf8("densButton"))
        self.gridLayout.addWidget(self.densButton, 6, 6, 1, 1)
        self.inclButton = QtGui.QPushButton(galmod)
        self.inclButton.setText(_fromUtf8(""))
        self.inclButton.setIcon(icon)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName(_fromUtf8("inclButton"))
        self.gridLayout.addWidget(self.inclButton, 8, 6, 1, 1)
        self.inclLine = QtGui.QLineEdit(galmod)
        self.inclLine.setObjectName(_fromUtf8("inclLine"))
        self.gridLayout.addWidget(self.inclLine, 8, 1, 1, 5)
        self.label_14 = QtGui.QLabel(galmod)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 13, 0, 1, 1)
        self.iseedLine = QtGui.QLineEdit(galmod)
        self.iseedLine.setObjectName(_fromUtf8("iseedLine"))
        self.gridLayout.addWidget(self.iseedLine, 13, 1, 1, 1)
        self.drvalLine = QtGui.QLineEdit(galmod)
        self.drvalLine.setObjectName(_fromUtf8("drvalLine"))
        self.gridLayout.addWidget(self.drvalLine, 2, 1, 1, 1)
        self.label = QtGui.QLabel(galmod)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.xcentreLine = QtGui.QLineEdit(galmod)
        self.xcentreLine.setObjectName(_fromUtf8("xcentreLine"))
        self.gridLayout.addWidget(self.xcentreLine, 0, 1, 1, 1)
        self.radiiButton = QtGui.QPushButton(galmod)
        self.radiiButton.setText(_fromUtf8(""))
        self.radiiButton.setIcon(icon)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName(_fromUtf8("radiiButton"))
        self.gridLayout.addWidget(self.radiiButton, 3, 6, 1, 1)
        self.label_16 = QtGui.QLabel(galmod)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(galmod)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(galmod)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.vrotLine = QtGui.QLineEdit(galmod)
        self.vrotLine.setObjectName(_fromUtf8("vrotLine"))
        self.gridLayout.addWidget(self.vrotLine, 4, 1, 1, 5)
        self.zoButton = QtGui.QPushButton(galmod)
        self.zoButton.setText(_fromUtf8(""))
        self.zoButton.setIcon(icon)
        self.zoButton.setIconSize(QtCore.QSize(20, 20))
        self.zoButton.setObjectName(_fromUtf8("zoButton"))
        self.gridLayout.addWidget(self.zoButton, 7, 6, 1, 1)
        self.vdispLine = QtGui.QLineEdit(galmod)
        self.vdispLine.setObjectName(_fromUtf8("vdispLine"))
        self.gridLayout.addWidget(self.vdispLine, 5, 1, 1, 5)
        self.emptyCheck = QtGui.QCheckBox(galmod)
        self.emptyCheck.setChecked(True)
        self.emptyCheck.setObjectName(_fromUtf8("emptyCheck"))
        self.gridLayout.addWidget(self.emptyCheck, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(galmod)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.vdispButton = QtGui.QPushButton(galmod)
        self.vdispButton.setText(_fromUtf8(""))
        self.vdispButton.setIcon(icon)
        self.vdispButton.setIconSize(QtCore.QSize(20, 20))
        self.vdispButton.setObjectName(_fromUtf8("vdispButton"))
        self.gridLayout.addWidget(self.vdispButton, 5, 6, 1, 1)
        self.nvLine = QtGui.QLineEdit(galmod)
        self.nvLine.setObjectName(_fromUtf8("nvLine"))
        self.gridLayout.addWidget(self.nvLine, 10, 5, 1, 1)
        self.radiiLine = QtGui.QLineEdit(galmod)
        self.radiiLine.setObjectName(_fromUtf8("radiiLine"))
        self.gridLayout.addWidget(self.radiiLine, 3, 1, 1, 5)
        self.ycentreLine = QtGui.QLineEdit(galmod)
        self.ycentreLine.setObjectName(_fromUtf8("ycentreLine"))
        self.gridLayout.addWidget(self.ycentreLine, 0, 3, 1, 1)
        self.layerBox = QtGui.QComboBox(galmod)
        self.layerBox.setObjectName(_fromUtf8("layerBox"))
        self.layerBox.addItem(_fromUtf8(""))
        self.layerBox.addItem(_fromUtf8(""))
        self.layerBox.addItem(_fromUtf8(""))
        self.layerBox.addItem(_fromUtf8(""))
        self.layerBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.layerBox, 11, 5, 1, 1)
        self.cmode1Radio = QtGui.QRadioButton(galmod)
        self.cmode1Radio.setObjectName(_fromUtf8("cmode1Radio"))
        self.buttonGroup1 = QtGui.QButtonGroup(galmod)
        self.buttonGroup1.setObjectName(_fromUtf8("buttonGroup1"))
        self.buttonGroup1.addButton(self.cmode1Radio)
        self.gridLayout.addWidget(self.cmode1Radio, 12, 1, 1, 1)
        self.paButton = QtGui.QPushButton(galmod)
        self.paButton.setText(_fromUtf8(""))
        self.paButton.setIcon(icon)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName(_fromUtf8("paButton"))
        self.gridLayout.addWidget(self.paButton, 9, 6, 1, 1)
        self.zoLine = QtGui.QLineEdit(galmod)
        self.zoLine.setObjectName(_fromUtf8("zoLine"))
        self.gridLayout.addWidget(self.zoLine, 7, 1, 1, 5)
        self.label_8 = QtGui.QLabel(galmod)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_6 = QtGui.QLabel(galmod)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(galmod)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 10, 3, 1, 1)
        self.label_12 = QtGui.QLabel(galmod)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 10, 4, 1, 1)
        self.cdensLine = QtGui.QLineEdit(galmod)
        self.cdensLine.setObjectName(_fromUtf8("cdensLine"))
        self.gridLayout.addWidget(self.cdensLine, 10, 1, 1, 1)
        self.paLine = QtGui.QLineEdit(galmod)
        self.paLine.setObjectName(_fromUtf8("paLine"))
        self.gridLayout.addWidget(self.paLine, 9, 1, 1, 5)
        self.cmode0Radio = QtGui.QRadioButton(galmod)
        self.cmode0Radio.setChecked(True)
        self.cmode0Radio.setObjectName(_fromUtf8("cmode0Radio"))
        self.buttonGroup1.addButton(self.cmode0Radio)
        self.gridLayout.addWidget(self.cmode0Radio, 11, 1, 1, 1)
        self.label_13 = QtGui.QLabel(galmod)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 11, 4, 1, 1)
        self.checkSampVsys = QtGui.QCheckBox(galmod)
        self.checkSampVsys.setEnabled(False)
        self.checkSampVsys.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVsys.setObjectName(_fromUtf8("checkSampVsys"))
        self.gridLayout.addWidget(self.checkSampVsys, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(galmod)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.vrotButton = QtGui.QPushButton(galmod)
        self.vrotButton.setText(_fromUtf8(""))
        self.vrotButton.setIcon(icon)
        self.vrotButton.setIconSize(QtCore.QSize(20, 20))
        self.vrotButton.setObjectName(_fromUtf8("vrotButton"))
        self.gridLayout.addWidget(self.vrotButton, 4, 6, 1, 1)
        self.frame_2 = QtGui.QFrame(galmod)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.vsysLine = QtGui.QLineEdit(self.frame_2)
        self.vsysLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vsysLine.setObjectName(_fromUtf8("vsysLine"))
        self.horizontalLayout_2.addWidget(self.vsysLine)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 2)
        self.frame = QtGui.QFrame(galmod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.loadParamsButton = QtGui.QPushButton(self.frame)
        self.loadParamsButton.setObjectName(_fromUtf8("loadParamsButton"))
        self.gridLayout_2.addWidget(self.loadParamsButton, 0, 0, 1, 1)
        self.saveParamsButton = QtGui.QPushButton(self.frame)
        self.saveParamsButton.setObjectName(_fromUtf8("saveParamsButton"))
        self.gridLayout_2.addWidget(self.saveParamsButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 14, 1, 1, 3)
        self.getRotcurColumnsButton = QtGui.QPushButton(galmod)
        self.getRotcurColumnsButton.setObjectName(_fromUtf8("getRotcurColumnsButton"))
        self.gridLayout.addWidget(self.getRotcurColumnsButton, 14, 6, 1, 2)

        self.retranslateUi(galmod)
        QtCore.QMetaObject.connectSlotsByName(galmod)
        galmod.setTabOrder(self.xcentreLine, self.ycentreLine)
        galmod.setTabOrder(self.ycentreLine, self.checkSampCentre)
        galmod.setTabOrder(self.checkSampCentre, self.vsysLine)
        galmod.setTabOrder(self.vsysLine, self.emptyCheck)
        galmod.setTabOrder(self.emptyCheck, self.checkSampVsys)
        galmod.setTabOrder(self.checkSampVsys, self.drvalLine)
        galmod.setTabOrder(self.drvalLine, self.radiiLine)
        galmod.setTabOrder(self.radiiLine, self.radiiButton)
        galmod.setTabOrder(self.radiiButton, self.checkSampRadii)
        galmod.setTabOrder(self.checkSampRadii, self.vrotLine)
        galmod.setTabOrder(self.vrotLine, self.vrotButton)
        galmod.setTabOrder(self.vrotButton, self.checkSampVrot)
        galmod.setTabOrder(self.checkSampVrot, self.vdispLine)
        galmod.setTabOrder(self.vdispLine, self.vdispButton)
        galmod.setTabOrder(self.vdispButton, self.densLine)
        galmod.setTabOrder(self.densLine, self.densButton)
        galmod.setTabOrder(self.densButton, self.zoLine)
        galmod.setTabOrder(self.zoLine, self.zoButton)
        galmod.setTabOrder(self.zoButton, self.inclLine)
        galmod.setTabOrder(self.inclLine, self.inclButton)
        galmod.setTabOrder(self.inclButton, self.paLine)
        galmod.setTabOrder(self.paLine, self.paButton)
        galmod.setTabOrder(self.paButton, self.cdensLine)
        galmod.setTabOrder(self.cdensLine, self.nvLine)
        galmod.setTabOrder(self.nvLine, self.cmode0Radio)
        galmod.setTabOrder(self.cmode0Radio, self.layerBox)
        galmod.setTabOrder(self.layerBox, self.cmode1Radio)
        galmod.setTabOrder(self.cmode1Radio, self.iseedLine)
        galmod.setTabOrder(self.iseedLine, self.loadParamsButton)
        galmod.setTabOrder(self.loadParamsButton, self.saveParamsButton)

    def retranslateUi(self, galmod):
        galmod.setWindowTitle(_translate("galmod", "Frame", None))
        self.label_4.setText(_translate("galmod", "VROT", None))
        self.checkSampCentre.setText(_translate("galmod", "SAMP", None))
        self.label_7.setText(_translate("galmod", "Z0", None))
        self.checkSampRadii.setText(_translate("galmod", "SAMP", None))
        self.label_9.setText(_translate("galmod", "PA", None))
        self.checkSampVrot.setText(_translate("galmod", "SAMP", None))
        self.label_14.setText(_translate("galmod", "ISEED", None))
        self.label.setText(_translate("galmod", "CENTRE", None))
        self.label_16.setText(_translate("galmod", "DRVAL3", None))
        self.label_5.setText(_translate("galmod", "VDISP", None))
        self.label_10.setText(_translate("galmod", "CDENS", None))
        self.emptyCheck.setText(_translate("galmod", "EMPTY", None))
        self.label_2.setText(_translate("galmod", "RADII", None))
        self.layerBox.setItemText(0, _translate("galmod", "Gaussian", None))
        self.layerBox.setItemText(1, _translate("galmod", "Sech2", None))
        self.layerBox.setItemText(2, _translate("galmod", "Exponential", None))
        self.layerBox.setItemText(3, _translate("galmod", "Lorentzian", None))
        self.layerBox.setItemText(4, _translate("galmod", "Box", None))
        self.cmode1Radio.setText(_translate("galmod", "CMODE 1", None))
        self.label_8.setText(_translate("galmod", "INCL", None))
        self.label_6.setText(_translate("galmod", "DENS", None))
        self.label_11.setText(_translate("galmod", "10^20 atoms/cm^2", None))
        self.label_12.setText(_translate("galmod", "NV", None))
        self.cmode0Radio.setText(_translate("galmod", "CMODE 0", None))
        self.label_13.setText(_translate("galmod", "Layer Type", None))
        self.checkSampVsys.setText(_translate("galmod", "SAMP", None))
        self.label_3.setText(_translate("galmod", "VSYS", None))
        self.label_15.setText(_translate("galmod", "KM/S", None))
        self.loadParamsButton.setText(_translate("galmod", "Load values", None))
        self.saveParamsButton.setText(_translate("galmod", "Save values", None))
        self.getRotcurColumnsButton.setText(_translate("galmod", "Load rotcur set table", None))

import resources_rc
