# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profil.ui'
#
# Created: Tue Dec 20 13:41:19 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_profil(object):
    def setupUi(self, profil):
        profil.setObjectName("profil")
        profil.resize(440, 201)
        profil.setFrameShape(QtGui.QFrame.NoFrame)
        profil.setFrameShadow(QtGui.QFrame.Plain)
        profil.setLineWidth(0)
        self.verticalLayout = QtGui.QVBoxLayout(profil)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtGui.QFrame(profil)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.contSetButton = QtGui.QPushButton(self.frame_2)
        self.contSetButton.setObjectName("contSetButton")
        self.gridLayout.addWidget(self.contSetButton, 0, 0, 1, 1)
        self.contSetLabel = QtGui.QLabel(self.frame_2)
        self.contSetLabel.setText("")
        self.contSetLabel.setObjectName("contSetLabel")
        self.gridLayout.addWidget(self.contSetLabel, 0, 1, 1, 1)
        self.contHeaderButton = QtGui.QPushButton(self.frame_2)
        self.contHeaderButton.setObjectName("contHeaderButton")
        self.gridLayout.addWidget(self.contHeaderButton, 0, 2, 1, 1)
        self.contBoxButton = QtGui.QPushButton(self.frame_2)
        self.contBoxButton.setObjectName("contBoxButton")
        self.gridLayout.addWidget(self.contBoxButton, 1, 0, 1, 1)
        self.contBoxLabel = QtGui.QLabel(self.frame_2)
        self.contBoxLabel.setText("")
        self.contBoxLabel.setObjectName("contBoxLabel")
        self.gridLayout.addWidget(self.contBoxLabel, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(profil)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.wtypeBox = QtGui.QComboBox(self.frame)
        self.wtypeBox.setObjectName("wtypeBox")
        self.wtypeBox.addItem("")
        self.wtypeBox.addItem("")
        self.wtypeBox.addItem("")
        self.wtypeBox.addItem("")
        self.gridLayout_2.addWidget(self.wtypeBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.thresholdLine = QtGui.QLineEdit(self.frame)
        self.thresholdLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.thresholdLine.setObjectName("thresholdLine")
        self.gridLayout_2.addWidget(self.thresholdLine, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.filenameLine = QtGui.QLineEdit(self.frame)
        self.filenameLine.setObjectName("filenameLine")
        self.gridLayout_2.addWidget(self.filenameLine, 2, 1, 1, 2)
        self.browserFileButton = QtGui.QPushButton(self.frame)
        self.browserFileButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserFileButton.setIcon(icon)
        self.browserFileButton.setIconSize(QtCore.QSize(20, 20))
        self.browserFileButton.setObjectName("browserFileButton")
        self.gridLayout_2.addWidget(self.browserFileButton, 2, 3, 1, 1)
        self.line_checkBox = QtGui.QCheckBox(self.frame)
        self.line_checkBox.setEnabled(False)
        self.line_checkBox.setObjectName("line_checkBox")
        self.gridLayout_2.addWidget(self.line_checkBox, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(profil)
        QtCore.QMetaObject.connectSlotsByName(profil)

    def retranslateUi(self, profil):
        profil.setWindowTitle(QtGui.QApplication.translate("profil", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.contSetButton.setText(QtGui.QApplication.translate("profil", "Continuum", None, QtGui.QApplication.UnicodeUTF8))
        self.contHeaderButton.setText(QtGui.QApplication.translate("profil", "HEADER", None, QtGui.QApplication.UnicodeUTF8))
        self.contBoxButton.setText(QtGui.QApplication.translate("profil", "BOX", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("profil", "WTYPE", None, QtGui.QApplication.UnicodeUTF8))
        self.wtypeBox.setItemText(0, QtGui.QApplication.translate("profil", "No Weighting", None, QtGui.QApplication.UnicodeUTF8))
        self.wtypeBox.setItemText(1, QtGui.QApplication.translate("profil", "Continuum weighting", None, QtGui.QApplication.UnicodeUTF8))
        self.wtypeBox.setItemText(2, QtGui.QApplication.translate("profil", "Continuum squared", None, QtGui.QApplication.UnicodeUTF8))
        self.wtypeBox.setItemText(3, QtGui.QApplication.translate("profil", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("profil", "THRESHOLD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("profil", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.line_checkBox.setText(QtGui.QApplication.translate("profil", "Line/continuum ratio", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
