# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reswri.ui'
#
# Created: Tue Mar  3 13:04:11 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_reswri(object):
    def setupUi(self, reswri):
        reswri.setObjectName(_fromUtf8("reswri"))
        reswri.resize(704, 604)
        reswri.setFrameShape(QtGui.QFrame.NoFrame)
        reswri.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(reswri)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(reswri)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.HIBoxButton = QtGui.QPushButton(self.frame)
        self.HIBoxButton.setObjectName(_fromUtf8("HIBoxButton"))
        self.gridLayout_2.addWidget(self.HIBoxButton, 1, 0, 1, 1)
        self.HISetButton = QtGui.QPushButton(self.frame)
        self.HISetButton.setObjectName(_fromUtf8("HISetButton"))
        self.gridLayout_2.addWidget(self.HISetButton, 0, 0, 1, 1)
        self.HISetHeaderButton = QtGui.QPushButton(self.frame)
        self.HISetHeaderButton.setObjectName(_fromUtf8("HISetHeaderButton"))
        self.gridLayout_2.addWidget(self.HISetHeaderButton, 0, 2, 1, 1)
        self.HISetLabel = QtGui.QLabel(self.frame)
        self.HISetLabel.setText(_fromUtf8(""))
        self.HISetLabel.setObjectName(_fromUtf8("HISetLabel"))
        self.gridLayout_2.addWidget(self.HISetLabel, 0, 1, 1, 1)
        self.HIBoxLabel = QtGui.QLabel(self.frame)
        self.HIBoxLabel.setText(_fromUtf8(""))
        self.HIBoxLabel.setObjectName(_fromUtf8("HIBoxLabel"))
        self.gridLayout_2.addWidget(self.HIBoxLabel, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(reswri)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setMargin(9)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 10, 3, 1, 1)
        self.vexpLine = QtGui.QLineEdit(self.frame_2)
        self.vexpLine.setObjectName(_fromUtf8("vexpLine"))
        self.gridLayout.addWidget(self.vexpLine, 7, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.kinematicButton = QtGui.QPushButton(self.frame_2)
        self.kinematicButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kinematicButton.setIcon(icon)
        self.kinematicButton.setIconSize(QtCore.QSize(20, 20))
        self.kinematicButton.setObjectName(_fromUtf8("kinematicButton"))
        self.gridLayout.addWidget(self.kinematicButton, 12, 5, 1, 1)
        self.checkSampVrot = QtGui.QCheckBox(self.frame_2)
        self.checkSampVrot.setEnabled(False)
        self.checkSampVrot.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVrot.setObjectName(_fromUtf8("checkSampVrot"))
        self.gridLayout.addWidget(self.checkSampVrot, 4, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.inclLine = QtGui.QLineEdit(self.frame_2)
        self.inclLine.setObjectName(_fromUtf8("inclLine"))
        self.gridLayout.addWidget(self.inclLine, 9, 1, 1, 3)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.xcentreLine = QtGui.QLineEdit(self.frame_3)
        self.xcentreLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xcentreLine.setObjectName(_fromUtf8("xcentreLine"))
        self.horizontalLayout.addWidget(self.xcentreLine)
        self.ycentreLine = QtGui.QLineEdit(self.frame_3)
        self.ycentreLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ycentreLine.setObjectName(_fromUtf8("ycentreLine"))
        self.horizontalLayout.addWidget(self.ycentreLine)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)
        self.surfaceButton = QtGui.QPushButton(self.frame_2)
        self.surfaceButton.setEnabled(False)
        self.surfaceButton.setText(_fromUtf8(""))
        self.surfaceButton.setIcon(icon)
        self.surfaceButton.setIconSize(QtCore.QSize(20, 20))
        self.surfaceButton.setObjectName(_fromUtf8("surfaceButton"))
        self.gridLayout.addWidget(self.surfaceButton, 13, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.radiiLine = QtGui.QLineEdit(self.frame_2)
        self.radiiLine.setObjectName(_fromUtf8("radiiLine"))
        self.gridLayout.addWidget(self.radiiLine, 3, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkSampVsys = QtGui.QCheckBox(self.frame_2)
        self.checkSampVsys.setEnabled(False)
        self.checkSampVsys.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVsys.setObjectName(_fromUtf8("checkSampVsys"))
        self.gridLayout.addWidget(self.checkSampVsys, 2, 4, 1, 1)
        self.bunitLine = QtGui.QLineEdit(self.frame_2)
        self.bunitLine.setObjectName(_fromUtf8("bunitLine"))
        self.gridLayout.addWidget(self.bunitLine, 0, 1, 1, 1)
        self.paCheck = QtGui.QCheckBox(self.frame_2)
        self.paCheck.setObjectName(_fromUtf8("paCheck"))
        self.gridLayout.addWidget(self.paCheck, 8, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.vrotButton = QtGui.QPushButton(self.frame_2)
        self.vrotButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vrotButton.setIcon(icon1)
        self.vrotButton.setIconSize(QtCore.QSize(20, 20))
        self.vrotButton.setObjectName(_fromUtf8("vrotButton"))
        self.gridLayout.addWidget(self.vrotButton, 4, 4, 1, 1)
        self.vsysCheck = QtGui.QCheckBox(self.frame_2)
        self.vsysCheck.setObjectName(_fromUtf8("vsysCheck"))
        self.gridLayout.addWidget(self.vsysCheck, 2, 3, 1, 1)
        self.vrotCheck = QtGui.QCheckBox(self.frame_2)
        self.vrotCheck.setObjectName(_fromUtf8("vrotCheck"))
        self.gridLayout.addWidget(self.vrotCheck, 4, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.paLine = QtGui.QLineEdit(self.frame_2)
        self.paLine.setObjectName(_fromUtf8("paLine"))
        self.gridLayout.addWidget(self.paLine, 8, 1, 1, 3)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.inclCheck = QtGui.QCheckBox(self.frame_2)
        self.inclCheck.setObjectName(_fromUtf8("inclCheck"))
        self.gridLayout.addWidget(self.inclCheck, 9, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.paButton = QtGui.QPushButton(self.frame_2)
        self.paButton.setText(_fromUtf8(""))
        self.paButton.setIcon(icon1)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName(_fromUtf8("paButton"))
        self.gridLayout.addWidget(self.paButton, 8, 4, 1, 1)
        self.widthsButton = QtGui.QPushButton(self.frame_2)
        self.widthsButton.setText(_fromUtf8(""))
        self.widthsButton.setIcon(icon1)
        self.widthsButton.setIconSize(QtCore.QSize(20, 20))
        self.widthsButton.setObjectName(_fromUtf8("widthsButton"))
        self.gridLayout.addWidget(self.widthsButton, 5, 4, 1, 1)
        self.fitorderLine = QtGui.QLineEdit(self.frame_2)
        self.fitorderLine.setObjectName(_fromUtf8("fitorderLine"))
        self.gridLayout.addWidget(self.fitorderLine, 11, 4, 1, 1)
        self.vrotLine = QtGui.QLineEdit(self.frame_2)
        self.vrotLine.setObjectName(_fromUtf8("vrotLine"))
        self.gridLayout.addWidget(self.vrotLine, 4, 1, 1, 3)
        self.vsysLine = QtGui.QLineEdit(self.frame_2)
        self.vsysLine.setObjectName(_fromUtf8("vsysLine"))
        self.gridLayout.addWidget(self.vsysLine, 2, 1, 1, 1)
        self.centreCheck = QtGui.QCheckBox(self.frame_2)
        self.centreCheck.setObjectName(_fromUtf8("centreCheck"))
        self.gridLayout.addWidget(self.centreCheck, 1, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 11, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 10, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.widthsLine = QtGui.QLineEdit(self.frame_2)
        self.widthsLine.setObjectName(_fromUtf8("widthsLine"))
        self.gridLayout.addWidget(self.widthsLine, 5, 1, 1, 3)
        self.fittoleranceLine = QtGui.QLineEdit(self.frame_2)
        self.fittoleranceLine.setObjectName(_fromUtf8("fittoleranceLine"))
        self.gridLayout.addWidget(self.fittoleranceLine, 10, 4, 1, 1)
        self.inclButton = QtGui.QPushButton(self.frame_2)
        self.inclButton.setText(_fromUtf8(""))
        self.inclButton.setIcon(icon1)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName(_fromUtf8("inclButton"))
        self.gridLayout.addWidget(self.inclButton, 9, 4, 1, 1)
        self.vexpButton = QtGui.QPushButton(self.frame_2)
        self.vexpButton.setText(_fromUtf8(""))
        self.vexpButton.setIcon(icon1)
        self.vexpButton.setIconSize(QtCore.QSize(20, 20))
        self.vexpButton.setObjectName(_fromUtf8("vexpButton"))
        self.gridLayout.addWidget(self.vexpButton, 7, 4, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(self.frame_2)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName(_fromUtf8("checkSampCentre"))
        self.gridLayout.addWidget(self.checkSampCentre, 1, 4, 1, 1)
        self.vexpCheck = QtGui.QCheckBox(self.frame_2)
        self.vexpCheck.setObjectName(_fromUtf8("vexpCheck"))
        self.gridLayout.addWidget(self.vexpCheck, 7, 5, 1, 1)
        self.freeangleLine = QtGui.QLineEdit(self.frame_2)
        self.freeangleLine.setObjectName(_fromUtf8("freeangleLine"))
        self.gridLayout.addWidget(self.freeangleLine, 10, 1, 1, 1)
        self.checkSampRadii = QtGui.QCheckBox(self.frame_2)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampRadii.setObjectName(_fromUtf8("checkSampRadii"))
        self.gridLayout.addWidget(self.checkSampRadii, 3, 5, 1, 1)
        self.sideBox = QtGui.QComboBox(self.frame_2)
        self.sideBox.setObjectName(_fromUtf8("sideBox"))
        self.sideBox.addItem(_fromUtf8(""))
        self.sideBox.addItem(_fromUtf8(""))
        self.sideBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.sideBox, 0, 5, 1, 1)
        self.radiiButton = QtGui.QPushButton(self.frame_2)
        self.radiiButton.setText(_fromUtf8(""))
        self.radiiButton.setIcon(icon1)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName(_fromUtf8("radiiButton"))
        self.gridLayout.addWidget(self.radiiButton, 3, 4, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadParamsButton = QtGui.QPushButton(self.frame_4)
        self.loadParamsButton.setObjectName(_fromUtf8("loadParamsButton"))
        self.horizontalLayout_2.addWidget(self.loadParamsButton)
        self.saveParamsButton = QtGui.QPushButton(self.frame_4)
        self.saveParamsButton.setObjectName(_fromUtf8("saveParamsButton"))
        self.horizontalLayout_2.addWidget(self.saveParamsButton)
        self.gridLayout.addWidget(self.frame_4, 15, 0, 1, 2)
        self.surfaceLabel = QtGui.QLabel(self.frame_2)
        self.surfaceLabel.setEnabled(False)
        self.surfaceLabel.setObjectName(_fromUtf8("surfaceLabel"))
        self.gridLayout.addWidget(self.surfaceLabel, 13, 0, 1, 2)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 12, 0, 1, 2)
        self.kinematicLine = QtGui.QLineEdit(self.frame_2)
        self.kinematicLine.setObjectName(_fromUtf8("kinematicLine"))
        self.gridLayout.addWidget(self.kinematicLine, 12, 2, 1, 3)
        self.surfaceLine = QtGui.QLineEdit(self.frame_2)
        self.surfaceLine.setEnabled(False)
        self.surfaceLine.setObjectName(_fromUtf8("surfaceLine"))
        self.gridLayout.addWidget(self.surfaceLine, 13, 2, 1, 3)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(reswri)
        QtCore.QMetaObject.connectSlotsByName(reswri)

    def retranslateUi(self, reswri):
        reswri.setWindowTitle(_translate("reswri", "Frame", None))
        self.HIBoxButton.setText(_translate("reswri", "BOX", None))
        self.HISetButton.setText(_translate("reswri", "HI", None))
        self.HISetHeaderButton.setText(_translate("reswri", "HEADER", None))
        self.label_14.setText(_translate("reswri", "FIT TOLERANCE", None))
        self.label_8.setText(_translate("reswri", "RADII", None))
        self.checkSampVrot.setText(_translate("reswri", "SAMP", None))
        self.label_9.setText(_translate("reswri", "VEXP", None))
        self.label_6.setText(_translate("reswri", "SIDE", None))
        self.label_12.setText(_translate("reswri", "FREEANGLE", None))
        self.label.setText(_translate("reswri", "WIDTHS", None))
        self.label_7.setText(_translate("reswri", "KM/S", None))
        self.label_5.setText(_translate("reswri", "VSYS", None))
        self.checkSampVsys.setText(_translate("reswri", "SAMP", None))
        self.paCheck.setText(_translate("reswri", "Fixed", None))
        self.label_3.setText(_translate("reswri", "BUNIT", None))
        self.vsysCheck.setText(_translate("reswri", "Fixed", None))
        self.vrotCheck.setText(_translate("reswri", "Fixed", None))
        self.label_2.setText(_translate("reswri", "VROT", None))
        self.label_10.setText(_translate("reswri", "PA", None))
        self.inclCheck.setText(_translate("reswri", "Fixed", None))
        self.label_11.setText(_translate("reswri", "INCL", None))
        self.centreCheck.setText(_translate("reswri", "Fixed", None))
        self.label_16.setText(_translate("reswri", "FIT ORDER", None))
        self.label_13.setText(_translate("reswri", "DEG", None))
        self.label_4.setText(_translate("reswri", "CENTRE", None))
        self.checkSampCentre.setText(_translate("reswri", "SAMP", None))
        self.vexpCheck.setText(_translate("reswri", "Fixed", None))
        self.checkSampRadii.setText(_translate("reswri", "SAMP", None))
        self.sideBox.setItemText(0, _translate("reswri", "Both", None))
        self.sideBox.setItemText(1, _translate("reswri", "Approaching", None))
        self.sideBox.setItemText(2, _translate("reswri", "Receding", None))
        self.loadParamsButton.setText(_translate("reswri", "Load values", None))
        self.saveParamsButton.setText(_translate("reswri", "Save values", None))
        self.surfaceLabel.setText(_translate("reswri", "Surface density harmonic coefficients", None))
        self.label_15.setText(_translate("reswri", "Kinematic harmonic coefficients", None))

import resources_rc
