# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rotcur.ui'
#
# Created: Wed Oct 29 12:04:45 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_rotcur(object):
    def setupUi(self, rotcur):
        rotcur.setObjectName(_fromUtf8("rotcur"))
        rotcur.resize(725, 573)
        rotcur.setFrameShape(QtGui.QFrame.NoFrame)
        rotcur.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(rotcur)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(rotcur)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkSampVrot = QtGui.QCheckBox(self.frame_2)
        self.checkSampVrot.setEnabled(False)
        self.checkSampVrot.setToolTip(_fromUtf8(""))
        self.checkSampVrot.setWhatsThis(_fromUtf8(""))
        self.checkSampVrot.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVrot.setObjectName(_fromUtf8("checkSampVrot"))
        self.gridLayout.addWidget(self.checkSampVrot, 4, 8, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.bunitLine = QtGui.QLineEdit(self.frame_2)
        self.bunitLine.setMaximumSize(QtCore.QSize(70, 16777215))
        self.bunitLine.setObjectName(_fromUtf8("bunitLine"))
        self.gridLayout.addWidget(self.bunitLine, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.radiiLine = QtGui.QLineEdit(self.frame_2)
        self.radiiLine.setObjectName(_fromUtf8("radiiLine"))
        self.gridLayout.addWidget(self.radiiLine, 3, 2, 1, 3)
        self.radiiButton = QtGui.QPushButton(self.frame_2)
        self.radiiButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radiiButton.setIcon(icon)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName(_fromUtf8("radiiButton"))
        self.gridLayout.addWidget(self.radiiButton, 3, 6, 1, 1)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.widthsLine = QtGui.QLineEdit(self.frame_2)
        self.widthsLine.setObjectName(_fromUtf8("widthsLine"))
        self.gridLayout.addWidget(self.widthsLine, 5, 2, 1, 3)
        self.widthsButton = QtGui.QPushButton(self.frame_2)
        self.widthsButton.setText(_fromUtf8(""))
        self.widthsButton.setIcon(icon)
        self.widthsButton.setIconSize(QtCore.QSize(20, 20))
        self.widthsButton.setObjectName(_fromUtf8("widthsButton"))
        self.gridLayout.addWidget(self.widthsButton, 5, 6, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 11, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.vexpLine = QtGui.QLineEdit(self.frame_2)
        self.vexpLine.setObjectName(_fromUtf8("vexpLine"))
        self.gridLayout.addWidget(self.vexpLine, 7, 2, 1, 3)
        self.vexpButton = QtGui.QPushButton(self.frame_2)
        self.vexpButton.setText(_fromUtf8(""))
        self.vexpButton.setIcon(icon)
        self.vexpButton.setIconSize(QtCore.QSize(20, 20))
        self.vexpButton.setObjectName(_fromUtf8("vexpButton"))
        self.gridLayout.addWidget(self.vexpButton, 7, 6, 1, 1)
        self.vexpCheck = QtGui.QCheckBox(self.frame_2)
        self.vexpCheck.setObjectName(_fromUtf8("vexpCheck"))
        self.gridLayout.addWidget(self.vexpCheck, 7, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.paLine = QtGui.QLineEdit(self.frame_2)
        self.paLine.setObjectName(_fromUtf8("paLine"))
        self.gridLayout.addWidget(self.paLine, 8, 2, 1, 3)
        self.paButton = QtGui.QPushButton(self.frame_2)
        self.paButton.setText(_fromUtf8(""))
        self.paButton.setIcon(icon)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName(_fromUtf8("paButton"))
        self.gridLayout.addWidget(self.paButton, 8, 6, 1, 1)
        self.paCheck = QtGui.QCheckBox(self.frame_2)
        self.paCheck.setObjectName(_fromUtf8("paCheck"))
        self.gridLayout.addWidget(self.paCheck, 8, 7, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.inclLine = QtGui.QLineEdit(self.frame_2)
        self.inclLine.setObjectName(_fromUtf8("inclLine"))
        self.gridLayout.addWidget(self.inclLine, 9, 2, 1, 3)
        self.inclButton = QtGui.QPushButton(self.frame_2)
        self.inclButton.setText(_fromUtf8(""))
        self.inclButton.setIcon(icon)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName(_fromUtf8("inclButton"))
        self.gridLayout.addWidget(self.inclButton, 9, 6, 1, 1)
        self.inclCheck = QtGui.QCheckBox(self.frame_2)
        self.inclCheck.setObjectName(_fromUtf8("inclCheck"))
        self.gridLayout.addWidget(self.inclCheck, 9, 7, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.freeangleLine = QtGui.QLineEdit(self.frame_2)
        self.freeangleLine.setObjectName(_fromUtf8("freeangleLine"))
        self.gridLayout.addWidget(self.freeangleLine, 10, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 10, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 10, 4, 1, 1)
        self.fittoleranceLine = QtGui.QLineEdit(self.frame_2)
        self.fittoleranceLine.setObjectName(_fromUtf8("fittoleranceLine"))
        self.gridLayout.addWidget(self.fittoleranceLine, 10, 6, 1, 1)
        self.saveParamsButton = QtGui.QPushButton(self.frame_2)
        self.saveParamsButton.setObjectName(_fromUtf8("saveParamsButton"))
        self.gridLayout.addWidget(self.saveParamsButton, 12, 0, 1, 1)
        self.weightBox = QtGui.QComboBox(self.frame_2)
        self.weightBox.setObjectName(_fromUtf8("weightBox"))
        self.weightBox.addItem(_fromUtf8(""))
        self.weightBox.addItem(_fromUtf8(""))
        self.weightBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.weightBox, 11, 2, 1, 1)
        self.vrotLine = QtGui.QLineEdit(self.frame_2)
        self.vrotLine.setObjectName(_fromUtf8("vrotLine"))
        self.gridLayout.addWidget(self.vrotLine, 4, 2, 1, 3)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.vrotButton = QtGui.QPushButton(self.frame_2)
        self.vrotButton.setText(_fromUtf8(""))
        self.vrotButton.setIcon(icon)
        self.vrotButton.setIconSize(QtCore.QSize(20, 20))
        self.vrotButton.setObjectName(_fromUtf8("vrotButton"))
        self.gridLayout.addWidget(self.vrotButton, 4, 6, 1, 1)
        self.vrotCheck = QtGui.QCheckBox(self.frame_2)
        self.vrotCheck.setObjectName(_fromUtf8("vrotCheck"))
        self.gridLayout.addWidget(self.vrotCheck, 4, 7, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 12, 2, 1, 1)
        self.loadParamsList = QtGui.QComboBox(self.frame_2)
        self.loadParamsList.setObjectName(_fromUtf8("loadParamsList"))
        self.gridLayout.addWidget(self.loadParamsList, 12, 3, 1, 1)
        self.checkSampRadii = QtGui.QCheckBox(self.frame_2)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampRadii.setObjectName(_fromUtf8("checkSampRadii"))
        self.gridLayout.addWidget(self.checkSampRadii, 3, 8, 1, 1)
        self.checkSampVsys = QtGui.QCheckBox(self.frame_2)
        self.checkSampVsys.setEnabled(False)
        self.checkSampVsys.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampVsys.setChecked(True)
        self.checkSampVsys.setObjectName(_fromUtf8("checkSampVsys"))
        self.gridLayout.addWidget(self.checkSampVsys, 2, 8, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(self.frame_2)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet(_fromUtf8("QCheckBox { color: green }"))
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName(_fromUtf8("checkSampCentre"))
        self.gridLayout.addWidget(self.checkSampCentre, 1, 8, 1, 1)
        self.vsysCheck = QtGui.QCheckBox(self.frame_2)
        self.vsysCheck.setObjectName(_fromUtf8("vsysCheck"))
        self.gridLayout.addWidget(self.vsysCheck, 2, 7, 1, 1)
        self.centreCheck = QtGui.QCheckBox(self.frame_2)
        self.centreCheck.setObjectName(_fromUtf8("centreCheck"))
        self.gridLayout.addWidget(self.centreCheck, 1, 7, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 6, 1, 1)
        self.vsysLine = QtGui.QLineEdit(self.frame_2)
        self.vsysLine.setObjectName(_fromUtf8("vsysLine"))
        self.gridLayout.addWidget(self.vsysLine, 2, 2, 1, 3)
        self.xcentreLine = QtGui.QLineEdit(self.frame_2)
        self.xcentreLine.setObjectName(_fromUtf8("xcentreLine"))
        self.gridLayout.addWidget(self.xcentreLine, 1, 2, 1, 2)
        self.ycentreLine = QtGui.QLineEdit(self.frame_2)
        self.ycentreLine.setObjectName(_fromUtf8("ycentreLine"))
        self.gridLayout.addWidget(self.ycentreLine, 1, 4, 1, 3)
        self.sideBox = QtGui.QComboBox(self.frame_2)
        self.sideBox.setObjectName(_fromUtf8("sideBox"))
        self.sideBox.addItem(_fromUtf8(""))
        self.sideBox.addItem(_fromUtf8(""))
        self.sideBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.sideBox, 0, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(rotcur)
        QtCore.QMetaObject.connectSlotsByName(rotcur)

    def retranslateUi(self, rotcur):
        rotcur.setWindowTitle(QtGui.QApplication.translate("rotcur", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVrot.setText(QtGui.QApplication.translate("rotcur", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("rotcur", "BUNIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("rotcur", "CENTRE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("rotcur", "VSYS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("rotcur", "RADII", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("rotcur", "WIDTHS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("rotcur", "WEIGHT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("rotcur", "VEXP", None, QtGui.QApplication.UnicodeUTF8))
        self.vexpCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("rotcur", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.paCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("rotcur", "INCL", None, QtGui.QApplication.UnicodeUTF8))
        self.inclCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("rotcur", "FREEANGLE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("rotcur", "DEG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("rotcur", "FIT TOLERANCE", None, QtGui.QApplication.UnicodeUTF8))
        self.saveParamsButton.setText(QtGui.QApplication.translate("rotcur", "Save values", None, QtGui.QApplication.UnicodeUTF8))
        self.weightBox.setItemText(0, QtGui.QApplication.translate("rotcur", "COSINE", None, QtGui.QApplication.UnicodeUTF8))
        self.weightBox.setItemText(1, QtGui.QApplication.translate("rotcur", "UNIFORM", None, QtGui.QApplication.UnicodeUTF8))
        self.weightBox.setItemText(2, QtGui.QApplication.translate("rotcur", "COS-SQUARED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("rotcur", "VROT", None, QtGui.QApplication.UnicodeUTF8))
        self.vrotCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("rotcur", "Load values:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampRadii.setText(QtGui.QApplication.translate("rotcur", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVsys.setText(QtGui.QApplication.translate("rotcur", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampCentre.setText(QtGui.QApplication.translate("rotcur", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.vsysCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.centreCheck.setText(QtGui.QApplication.translate("rotcur", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("rotcur", "KM/S", None, QtGui.QApplication.UnicodeUTF8))
        self.sideBox.setItemText(0, QtGui.QApplication.translate("rotcur", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.sideBox.setItemText(1, QtGui.QApplication.translate("rotcur", "Approaching", None, QtGui.QApplication.UnicodeUTF8))
        self.sideBox.setItemText(2, QtGui.QApplication.translate("rotcur", "Receding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("rotcur", "SIDE", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
