# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setbrowser.ui'
#
# Created: Mon Jun 17 11:13:30 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_setbrowser(object):
    def setupUi(self, setbrowser):
        setbrowser.setObjectName("setbrowser")
        setbrowser.resize(556, 386)
        self.gridLayout = QtGui.QGridLayout(setbrowser)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(setbrowser)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.browseButton = QtGui.QPushButton(setbrowser)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 0, 3, 1, 1)
        self.axisFrame = QtGui.QFrame(setbrowser)
        self.axisFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.axisFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.axisFrame.setObjectName("axisFrame")
        self.axesLayout = QtGui.QGridLayout(self.axisFrame)
        self.axesLayout.setObjectName("axesLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.axesLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.axisFrame, 3, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(setbrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 4)
        self.setpathLabel = QtGui.QLabel(setbrowser)
        self.setpathLabel.setText("")
        self.setpathLabel.setObjectName("setpathLabel")
        self.gridLayout.addWidget(self.setpathLabel, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(setbrowser)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.composerEnableButton = QtGui.QPushButton(setbrowser)
        self.composerEnableButton.setEnabled(False)
        self.composerEnableButton.setObjectName("composerEnableButton")
        self.gridLayout.addWidget(self.composerEnableButton, 2, 0, 1, 1)
        self.manualEditFrame = QtGui.QFrame(setbrowser)
        self.manualEditFrame.setEnabled(False)
        self.manualEditFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.manualEditFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.manualEditFrame.setObjectName("manualEditFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.manualEditFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.manualEditFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.subsetLine = QtGui.QLineEdit(self.manualEditFrame)
        self.subsetLine.setObjectName("subsetLine")
        self.gridLayout_2.addWidget(self.subsetLine, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.manualEditFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.boxLine = QtGui.QLineEdit(self.manualEditFrame)
        self.boxLine.setObjectName("boxLine")
        self.gridLayout_2.addWidget(self.boxLine, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.manualEditFrame, 5, 0, 3, 4)
        self.editEnableButton = QtGui.QPushButton(setbrowser)
        self.editEnableButton.setEnabled(True)
        self.editEnableButton.setObjectName("editEnableButton")
        self.gridLayout.addWidget(self.editEnableButton, 4, 0, 1, 1)
        self.setnameLine = QtGui.QLineEdit(setbrowser)
        self.setnameLine.setReadOnly(True)
        self.setnameLine.setObjectName("setnameLine")
        self.gridLayout.addWidget(self.setnameLine, 1, 1, 1, 1)
        self.headerButton = QtGui.QPushButton(setbrowser)
        self.headerButton.setObjectName("headerButton")
        self.gridLayout.addWidget(self.headerButton, 1, 3, 1, 1)

        self.retranslateUi(setbrowser)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), setbrowser.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), setbrowser.reject)
        QtCore.QMetaObject.connectSlotsByName(setbrowser)

    def retranslateUi(self, setbrowser):
        setbrowser.setWindowTitle(QtGui.QApplication.translate("setbrowser", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("setbrowser", "Set Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("setbrowser", "BROWSE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("setbrowser", "Set Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.composerEnableButton.setText(QtGui.QApplication.translate("setbrowser", "Compose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("setbrowser", "Set/subset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("setbrowser", "BOX", None, QtGui.QApplication.UnicodeUTF8))
        self.editEnableButton.setText(QtGui.QApplication.translate("setbrowser", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.headerButton.setText(QtGui.QApplication.translate("setbrowser", "HEADER", None, QtGui.QApplication.UnicodeUTF8))

