# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transform.ui'
#
# Created: Thu Aug  4 12:01:35 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_transform(object):
    def setupUi(self, transform):
        transform.setObjectName("transform")
        transform.resize(486, 300)
        transform.setFrameShape(QtGui.QFrame.NoFrame)
        transform.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(transform)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(transform)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.xposLine = QtGui.QLineEdit(self.groupBox)
        self.xposLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.xposLine.setObjectName("xposLine")
        self.horizontalLayout.addWidget(self.xposLine)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.yposLine = QtGui.QLineEdit(self.groupBox)
        self.yposLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.yposLine.setObjectName("yposLine")
        self.horizontalLayout.addWidget(self.yposLine)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.operationBox = QtGui.QComboBox(self.groupBox)
        self.operationBox.setObjectName("operationBox")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.operationBox.addItem("")
        self.horizontalLayout.addWidget(self.operationBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(transform)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.translxLine = QtGui.QLineEdit(self.groupBox_2)
        self.translxLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.translxLine.setObjectName("translxLine")
        self.gridLayout_2.addWidget(self.translxLine, 0, 1, 1, 1)
        self.translyLine = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translyLine.sizePolicy().hasHeightForWidth())
        self.translyLine.setSizePolicy(sizePolicy)
        self.translyLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.translyLine.setObjectName("translyLine")
        self.gridLayout_2.addWidget(self.translyLine, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.angleLine = QtGui.QLineEdit(self.groupBox_2)
        self.angleLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.angleLine.setObjectName("angleLine")
        self.gridLayout_2.addWidget(self.angleLine, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.scalexLine = QtGui.QLineEdit(self.groupBox_2)
        self.scalexLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.scalexLine.setObjectName("scalexLine")
        self.gridLayout_2.addWidget(self.scalexLine, 2, 1, 1, 1)
        self.scaleyLine = QtGui.QLineEdit(self.groupBox_2)
        self.scaleyLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.scaleyLine.setObjectName("scaleyLine")
        self.gridLayout_2.addWidget(self.scaleyLine, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.xshearLine = QtGui.QLineEdit(self.groupBox_2)
        self.xshearLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.xshearLine.setObjectName("xshearLine")
        self.gridLayout_2.addWidget(self.xshearLine, 3, 1, 1, 1)
        self.yshearLine = QtGui.QLineEdit(self.groupBox_2)
        self.yshearLine.setMaximumSize(QtCore.QSize(75, 16777215))
        self.yshearLine.setObjectName("yshearLine")
        self.gridLayout_2.addWidget(self.yshearLine, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(transform)
        QtCore.QMetaObject.connectSlotsByName(transform)

    def retranslateUi(self, transform):
        transform.setWindowTitle(QtGui.QApplication.translate("transform", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("transform", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("transform", "X POS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("transform", "Y POS", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(0, QtGui.QApplication.translate("transform", "Translation", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(1, QtGui.QApplication.translate("transform", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(2, QtGui.QApplication.translate("transform", "Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(3, QtGui.QApplication.translate("transform", "X Reflection", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(4, QtGui.QApplication.translate("transform", "Y Reflection", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(5, QtGui.QApplication.translate("transform", "PC Reflection", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(6, QtGui.QApplication.translate("transform", "X Shear", None, QtGui.QApplication.UnicodeUTF8))
        self.operationBox.setItemText(7, QtGui.QApplication.translate("transform", "Y Shear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("transform", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("transform", "TRANSLXY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("transform", "ANGLE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("transform", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("transform", "SCALEXY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("transform", "XSHEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("transform", "YSHEAR", None, QtGui.QApplication.UnicodeUTF8))

