# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewtask.ui'
#
# Created: Thu Apr 25 10:56:00 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_viewtask(object):
    def setupUi(self, viewtask):
        viewtask.setObjectName("viewtask")
        viewtask.resize(439, 309)
        self.verticalLayout = QtGui.QVBoxLayout(viewtask)
        self.verticalLayout.setObjectName("verticalLayout")
        self.insetFrame = QtGui.QFrame(viewtask)
        self.insetFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.insetFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.insetFrame.setObjectName("insetFrame")
        self.gridLayout = QtGui.QGridLayout(self.insetFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.insetButton = QtGui.QPushButton(self.insetFrame)
        self.insetButton.setObjectName("insetButton")
        self.gridLayout.addWidget(self.insetButton, 0, 0, 1, 1)
        self.headerButton = QtGui.QPushButton(self.insetFrame)
        self.headerButton.setObjectName("headerButton")
        self.gridLayout.addWidget(self.headerButton, 0, 2, 1, 1)
        self.boxButton = QtGui.QPushButton(self.insetFrame)
        self.boxButton.setObjectName("boxButton")
        self.gridLayout.addWidget(self.boxButton, 1, 0, 1, 1)
        self.insetLabel = QtGui.QLabel(self.insetFrame)
        self.insetLabel.setText("")
        self.insetLabel.setObjectName("insetLabel")
        self.gridLayout.addWidget(self.insetLabel, 0, 1, 1, 1)
        self.boxLabel = QtGui.QLabel(self.insetFrame)
        self.boxLabel.setText("")
        self.boxLabel.setObjectName("boxLabel")
        self.gridLayout.addWidget(self.boxLabel, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.insetFrame)
        self.frame = QtGui.QFrame(viewtask)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QVBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.frame)
        self.outsetFrame = QtGui.QFrame(viewtask)
        self.outsetFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.outsetFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.outsetFrame.setObjectName("outsetFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.outsetFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.outsetFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.outsetNameLine = QtGui.QLineEdit(self.outsetFrame)
        self.outsetNameLine.setObjectName("outsetNameLine")
        self.gridLayout_2.addWidget(self.outsetNameLine, 1, 1, 1, 3)
        self.label = QtGui.QLabel(self.outsetFrame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.replaceButton = QtGui.QPushButton(self.outsetFrame)
        self.replaceButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.replaceButton.setIcon(icon)
        self.replaceButton.setObjectName("replaceButton")
        self.gridLayout_2.addWidget(self.replaceButton, 1, 4, 1, 1)
        self.browserButton = QtGui.QPushButton(self.outsetFrame)
        self.browserButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserButton.setIcon(icon1)
        self.browserButton.setObjectName("browserButton")
        self.gridLayout_2.addWidget(self.browserButton, 0, 4, 1, 1)
        self.outsetPathLabel = QtGui.QLabel(self.outsetFrame)
        self.outsetPathLabel.setText("")
        self.outsetPathLabel.setObjectName("outsetPathLabel")
        self.gridLayout_2.addWidget(self.outsetPathLabel, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.outsetFrame)
        self.advise_panel = QtGui.QFrame(viewtask)
        self.advise_panel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advise_panel.sizePolicy().hasHeightForWidth())
        self.advise_panel.setSizePolicy(sizePolicy)
        self.advise_panel.setFrameShape(QtGui.QFrame.NoFrame)
        self.advise_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.advise_panel.setObjectName("advise_panel")
        self.advise_panel_layout = QtGui.QVBoxLayout(self.advise_panel)
        self.advise_panel_layout.setObjectName("advise_panel_layout")
        self.status = QtGui.QLabel(self.advise_panel)
        self.status.setText("")
        self.status.setObjectName("status")
        self.advise_panel_layout.addWidget(self.status)
        self.errorMsg = QtGui.QLabel(self.advise_panel)
        self.errorMsg.setText("")
        self.errorMsg.setObjectName("errorMsg")
        self.advise_panel_layout.addWidget(self.errorMsg)
        self.extra_panel = QtGui.QFrame(self.advise_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extra_panel.sizePolicy().hasHeightForWidth())
        self.extra_panel.setSizePolicy(sizePolicy)
        self.extra_panel.setFrameShape(QtGui.QFrame.NoFrame)
        self.extra_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.extra_panel.setObjectName("extra_panel")
        self.extra_panel_layout = QtGui.QVBoxLayout(self.extra_panel)
        self.extra_panel_layout.setObjectName("extra_panel_layout")
        self.advise_panel_layout.addWidget(self.extra_panel)
        self.verticalLayout.addWidget(self.advise_panel)
        self.buttonBox = QtGui.QDialogButtonBox(viewtask)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(viewtask)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), viewtask.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), viewtask.reject)
        QtCore.QMetaObject.connectSlotsByName(viewtask)

    def retranslateUi(self, viewtask):
        viewtask.setWindowTitle(QtGui.QApplication.translate("viewtask", "TASK", None, QtGui.QApplication.UnicodeUTF8))
        self.insetButton.setText(QtGui.QApplication.translate("viewtask", "INSET", None, QtGui.QApplication.UnicodeUTF8))
        self.headerButton.setText(QtGui.QApplication.translate("viewtask", "HEADER", None, QtGui.QApplication.UnicodeUTF8))
        self.boxButton.setText(QtGui.QApplication.translate("viewtask", "BOX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("viewtask", "Outset Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("viewtask", "Outset Path:", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
