# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'velfi.ui'
#
# Created: Thu Apr 25 11:02:30 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_velfi(object):
    def setupUi(self, velfi):
        velfi.setObjectName("velfi")
        velfi.resize(492, 329)
        velfi.setFrameShape(QtGui.QFrame.StyledPanel)
        velfi.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(velfi)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(velfi)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtGui.QLabel(velfi)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.vsysLine = QtGui.QLineEdit(velfi)
        self.vsysLine.setObjectName("vsysLine")
        self.gridLayout.addWidget(self.vsysLine, 2, 1, 1, 2)
        self.vsysButton = QtGui.QPushButton(velfi)
        self.vsysButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vsysButton.setIcon(icon)
        self.vsysButton.setIconSize(QtCore.QSize(20, 20))
        self.vsysButton.setObjectName("vsysButton")
        self.gridLayout.addWidget(self.vsysButton, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(velfi)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.vrotLine = QtGui.QLineEdit(velfi)
        self.vrotLine.setObjectName("vrotLine")
        self.gridLayout.addWidget(self.vrotLine, 4, 1, 1, 2)
        self.vrotButton = QtGui.QPushButton(velfi)
        self.vrotButton.setText("")
        self.vrotButton.setIcon(icon)
        self.vrotButton.setIconSize(QtCore.QSize(20, 20))
        self.vrotButton.setObjectName("vrotButton")
        self.gridLayout.addWidget(self.vrotButton, 4, 3, 1, 1)
        self.label_9 = QtGui.QLabel(velfi)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.vradLine = QtGui.QLineEdit(velfi)
        self.vradLine.setObjectName("vradLine")
        self.gridLayout.addWidget(self.vradLine, 5, 1, 1, 2)
        self.vradButton = QtGui.QPushButton(velfi)
        self.vradButton.setText("")
        self.vradButton.setIcon(icon)
        self.vradButton.setIconSize(QtCore.QSize(20, 20))
        self.vradButton.setObjectName("vradButton")
        self.gridLayout.addWidget(self.vradButton, 5, 3, 1, 1)
        self.label_10 = QtGui.QLabel(velfi)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.paLine = QtGui.QLineEdit(velfi)
        self.paLine.setObjectName("paLine")
        self.gridLayout.addWidget(self.paLine, 6, 1, 1, 2)
        self.paButton = QtGui.QPushButton(velfi)
        self.paButton.setText("")
        self.paButton.setIcon(icon)
        self.paButton.setIconSize(QtCore.QSize(20, 20))
        self.paButton.setObjectName("paButton")
        self.gridLayout.addWidget(self.paButton, 6, 3, 1, 1)
        self.label_11 = QtGui.QLabel(velfi)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.inclLine = QtGui.QLineEdit(velfi)
        self.inclLine.setObjectName("inclLine")
        self.gridLayout.addWidget(self.inclLine, 7, 1, 1, 2)
        self.inclButton = QtGui.QPushButton(velfi)
        self.inclButton.setText("")
        self.inclButton.setIcon(icon)
        self.inclButton.setIconSize(QtCore.QSize(20, 20))
        self.inclButton.setObjectName("inclButton")
        self.gridLayout.addWidget(self.inclButton, 7, 3, 1, 1)
        self.saveParamsButton = QtGui.QPushButton(velfi)
        self.saveParamsButton.setObjectName("saveParamsButton")
        self.gridLayout.addWidget(self.saveParamsButton, 8, 0, 1, 1)
        self.loadParamsButton = QtGui.QPushButton(velfi)
        self.loadParamsButton.setObjectName("loadParamsButton")
        self.gridLayout.addWidget(self.loadParamsButton, 8, 1, 1, 1)
        self.frame = QtGui.QFrame(velfi)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xcentreLine = QtGui.QLineEdit(self.frame)
        self.xcentreLine.setMaximumSize(QtCore.QSize(60, 16777215))
        self.xcentreLine.setObjectName("xcentreLine")
        self.horizontalLayout.addWidget(self.xcentreLine)
        self.ycentreLine = QtGui.QLineEdit(self.frame)
        self.ycentreLine.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ycentreLine.setObjectName("ycentreLine")
        self.horizontalLayout.addWidget(self.ycentreLine)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.checkSampVsys = QtGui.QCheckBox(velfi)
        self.checkSampVsys.setEnabled(False)
        self.checkSampVsys.setStyleSheet("QCheckBox { color: green }")
        self.checkSampVsys.setChecked(True)
        self.checkSampVsys.setObjectName("checkSampVsys")
        self.gridLayout.addWidget(self.checkSampVsys, 2, 4, 1, 1)
        self.checkSampVrot = QtGui.QCheckBox(velfi)
        self.checkSampVrot.setEnabled(False)
        self.checkSampVrot.setStyleSheet("QCheckBox { color: green }")
        self.checkSampVrot.setObjectName("checkSampVrot")
        self.gridLayout.addWidget(self.checkSampVrot, 4, 4, 1, 1)
        self.radiiLine = QtGui.QLineEdit(velfi)
        self.radiiLine.setObjectName("radiiLine")
        self.gridLayout.addWidget(self.radiiLine, 3, 1, 1, 2)
        self.label_8 = QtGui.QLabel(velfi)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.radiiButton = QtGui.QPushButton(velfi)
        self.radiiButton.setText("")
        self.radiiButton.setIcon(icon)
        self.radiiButton.setIconSize(QtCore.QSize(20, 20))
        self.radiiButton.setObjectName("radiiButton")
        self.gridLayout.addWidget(self.radiiButton, 3, 3, 1, 1)
        self.checkSampRadii = QtGui.QCheckBox(velfi)
        self.checkSampRadii.setEnabled(False)
        self.checkSampRadii.setStyleSheet("QCheckBox { color: green }")
        self.checkSampRadii.setObjectName("checkSampRadii")
        self.gridLayout.addWidget(self.checkSampRadii, 3, 4, 1, 1)
        self.checkSampCentre = QtGui.QCheckBox(velfi)
        self.checkSampCentre.setEnabled(False)
        self.checkSampCentre.setStyleSheet("QCheckBox { color: green }")
        self.checkSampCentre.setChecked(True)
        self.checkSampCentre.setObjectName("checkSampCentre")
        self.gridLayout.addWidget(self.checkSampCentre, 0, 2, 1, 1)

        self.retranslateUi(velfi)
        QtCore.QMetaObject.connectSlotsByName(velfi)

    def retranslateUi(self, velfi):
        velfi.setWindowTitle(QtGui.QApplication.translate("velfi", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("velfi", "CENTRE", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("velfi", "VSYS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("velfi", "VROT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("velfi", "VRAD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("velfi", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("velfi", "INCL", None, QtGui.QApplication.UnicodeUTF8))
        self.saveParamsButton.setText(QtGui.QApplication.translate("velfi", "SAVE PARAMS", None, QtGui.QApplication.UnicodeUTF8))
        self.loadParamsButton.setText(QtGui.QApplication.translate("velfi", "LOAD PARAMS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVsys.setText(QtGui.QApplication.translate("velfi", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampVrot.setText(QtGui.QApplication.translate("velfi", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("velfi", "RADII", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampRadii.setText(QtGui.QApplication.translate("velfi", "SAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSampCentre.setText(QtGui.QApplication.translate("velfi", "SAMP", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
